
fastlane_version "1.106.2"

default_platform :ios

platform :ios do

  lane :beta do
    incrementBuildNumberAndCommit
    gym(scheme: "Numbers", include_bitcode: false)
    pilot(skip_waiting_for_build_processing: true, team_id: "117886305")
  end

  def incrementBuildNumberAndCommit()
    increment_build_number(xcodeproj: 'Project/Numbers.xcodeproj')
    git_commit(path: ['Project/Numbers.xcodeproj/project.pbxproj',
      'Project/Numbers/Info.plist',
      'Project/NumbersTests/Info.plist',
      'Project/NumbersUITests/Info.plist'],
      message: "Testflight + ")
  end

end
